### ISSUE TITLE
node_ext2fs.cc fails to compile

### ISSUE THREAD

**Issue by Ereski** [balena-io/node-ext2fs#71] opened 2019-11-27 04:21 UTC
Two errors are preventing `node_ext2fs.cc` from compiling:

```
In file included from ../src/node_ext2fs.cc:5:
../src/ext2fs.h: At global scope:
../src/ext2fs.h:20:18: error: conflicting declaration ‘typedef uint64_t __u64’
   20 | typedef uint64_t __u64;
      |                  ^~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/asm/types.h:5,
                 from /usr/include/linux/types.h:5,
                 from /usr/include/linux/stat.h:5,
                 from /usr/include/bits/statx.h:30,
                 from /usr/include/sys/stat.h:446,
                 from .cache/node-gyp/13.2.0/include/node/uv/unix.h:26,
                 from .cache/node-gyp/13.2.0/include/node/uv.h:66,
                 from ../../nan/nan.h:52,
                 from ../src/node_ext2fs.cc:2:
/usr/include/asm-generic/int-ll64.h:31:42: note: previous declaration as ‘typedef long long unsigned int __u64’
   31 | __extension__ typedef unsigned long long __u64;
      |                  ^~~~~

../src/node_ext2fs.cc: In member function ‘virtual void ReadDirWorker::HandleOKCallback()’:
../src/node_ext2fs.cc:688:5: error: no matching function for call to ‘v8::Array::Set(uint32_t, v8::Local<v8::Object>)’
  688 |     );
      |     ^
```

```
$ node --version
v13.2.0
```

```
$ npm --version
6.12.1
```

```
$ node-gyp --version
v6.0.1
```

```
$ gcc --version
gcc (GCC) 9.2.0
```

**Comment by chrmoritz** [comment] 2019-11-28 16:50
The 2nd `v8::Array::Set` error, which is caused by `V8` API changes in Node.js 13 should be fixed with #70.

**Closed** 2020-01-07 15:43 UTC
